# Generated by Django 5.2.1 on 2025-05-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_gender_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_candidates',
            field=models.BooleanField(default=False, help_text='Can manage candidates (add, edit, delete)'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_voters',
            field=models.BooleanField(default=False, help_text='Can manage voters (add, edit, delete)'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_votings',
            field=models.BooleanField(default=False, help_text='Can manage votings (add, edit, delete)'),
        ),
    ]
